//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Game/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""CharacterController_B"",
            ""id"": ""a561b055-93b1-4145-beaa-cb3309eecba9"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""ad142f9e-4cc2-42f5-b036-e244b787377f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""686b0393-3e4a-427f-82f1-11eb89f9ef9b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Strike"",
                    ""type"": ""Button"",
                    ""id"": ""6ac7a28a-3dcf-4c29-b60b-5c78a81270ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Counter"",
                    ""type"": ""Button"",
                    ""id"": ""f94fa36b-227d-4371-b6f0-d798cb692c42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""85d8af99-2cbf-4ccb-b78a-478bfd074478"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f333d5cf-323a-4ffc-a09c-59e01b904084"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strike"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6167974-b71c-4fda-8abd-0b30dcd47ef0"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Counter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b284d8b-547c-46a0-9cfe-209514351d58"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterController_B
        m_CharacterController_B = asset.FindActionMap("CharacterController_B", throwIfNotFound: true);
        m_CharacterController_B_Move = m_CharacterController_B.FindAction("Move", throwIfNotFound: true);
        m_CharacterController_B_Look = m_CharacterController_B.FindAction("Look", throwIfNotFound: true);
        m_CharacterController_B_Strike = m_CharacterController_B.FindAction("Strike", throwIfNotFound: true);
        m_CharacterController_B_Counter = m_CharacterController_B.FindAction("Counter", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterController_B
    private readonly InputActionMap m_CharacterController_B;
    private List<ICharacterController_BActions> m_CharacterController_BActionsCallbackInterfaces = new List<ICharacterController_BActions>();
    private readonly InputAction m_CharacterController_B_Move;
    private readonly InputAction m_CharacterController_B_Look;
    private readonly InputAction m_CharacterController_B_Strike;
    private readonly InputAction m_CharacterController_B_Counter;
    public struct CharacterController_BActions
    {
        private @PlayerInput m_Wrapper;
        public CharacterController_BActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_CharacterController_B_Move;
        public InputAction @Look => m_Wrapper.m_CharacterController_B_Look;
        public InputAction @Strike => m_Wrapper.m_CharacterController_B_Strike;
        public InputAction @Counter => m_Wrapper.m_CharacterController_B_Counter;
        public InputActionMap Get() { return m_Wrapper.m_CharacterController_B; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterController_BActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterController_BActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterController_BActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterController_BActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Strike.started += instance.OnStrike;
            @Strike.performed += instance.OnStrike;
            @Strike.canceled += instance.OnStrike;
            @Counter.started += instance.OnCounter;
            @Counter.performed += instance.OnCounter;
            @Counter.canceled += instance.OnCounter;
        }

        private void UnregisterCallbacks(ICharacterController_BActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Strike.started -= instance.OnStrike;
            @Strike.performed -= instance.OnStrike;
            @Strike.canceled -= instance.OnStrike;
            @Counter.started -= instance.OnCounter;
            @Counter.performed -= instance.OnCounter;
            @Counter.canceled -= instance.OnCounter;
        }

        public void RemoveCallbacks(ICharacterController_BActions instance)
        {
            if (m_Wrapper.m_CharacterController_BActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterController_BActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterController_BActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterController_BActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterController_BActions @CharacterController_B => new CharacterController_BActions(this);
    public interface ICharacterController_BActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnStrike(InputAction.CallbackContext context);
        void OnCounter(InputAction.CallbackContext context);
    }
}
